version: '3'
services:
  postgres:
    image: postgres:13
    container_name: pg_pikpo
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_PORT}
    ports:
      - 5500:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_pikpo
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis-data:/data

  go-app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    environment:
      - PG_HOST=pg_pikpo
      - PG_PORT=5432
      - REDIS_HOST=redis_pikpo
      - REDIS_PORT=6379
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - postgres
