version: '3'
services:
  postgres:
    image: postgres:13.0-alpine
    container_name: pg_pikpo
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - 5500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - pikpo_net

  redis:
    image: redis
    container_name: redis_pikpo
    restart: always
    networks:
      - pikpo_net
    ports:
      - 6380:6379

  go-app:
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - PG_HOST=pg_pikpo
      - PG_PORT=5432
      - REDIS_HOST=redis_pikpo
      - REDIS_PORT=6379
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - postgres
    networks:
      - pikpo_net

volumes:
  postgres_data:
    driver: local

networks:
  pikpo_net:
    driver: bridge
